In [7]:
import numpy
arr = [1,23,45,5]
print(arr[2])

45


In [9]:
import numpy as np

array = np.arange(12).reshape(3, 4)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
import numpy as np

arr = np.random.rand(5, 5)
col_avg = np.mean(arr, axis=0)
print(col_avg)

[0.31043041 0.41618083 0.22379416 0.43362635 0.52678642]


In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
result = arr[arr > 5]
print(result)

[6 7 8 9]
